<link href="<?php echo $this->baseUrl().'/css/login.css'; ?>" media="all" rel="stylesheet" type="text/css" />
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<html>
<div class="log">	
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
  <div>
  <?php
if(!empty($this->form)) {
	$this->form->setAction($this->url());
	echo $this->form;
}
?>
</div></div>
  <div class="col-md-4"></div>
</div>

</div>
<html>
