<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<?php
echo $this->headTitle();
?>
</head>
	<body>
	<?php echo $this->render('_header.phtml') ?>
	<?php echo $this->layout()->content; ?>
	<?php echo $this->render('_footer.phtml') ?>
	</body>
</html>